[gcp_service_account]
type = "service_account"
project_id = "stella-project-ai"
private_key_id = "19fa4e719a0a55f8c9b20bb35a242a18940a38d4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDVS5gKuTd9hvzU
fmgYIBnhffOhk7DYvxf4yZUu5Z8HF+3sB1fpX3yTP2abmsYk4mzFsm+TJzRiQQiR
O8S4TTj9yzPbyLbCJNnR7GyZLyrVZWHfAy9Pt3ikekDehL4Xdx2nV1c+935yEFku
D/SINvAjrY6WQSIfpbdCKVKZ+lPcim7wwpYA3JwN6JqOdQtxmAykOuqCc2PGXHal
U/1A7ie82yzKkGHimnhV5GZRotk5hidpGBB17mxisCF1E6/p3dsJZKAyk5RSbpJZ
wt3WI86ChEjlZs10/5yvrDCgp7Wi3dJIEE99/UTDSpm9qH29JseU4aIMc0ozsTw6
Fj0Ugm3TAgMBAAECggEAAMa2Jm/XHltT5zgQi+nt/i6VqORfM+K6JRsisll+kymI
oZ/DN6Oz0dtctbtB9ldmmu+TzV7Kp4LiE5k6lYseZnoLVcTsuVcl/cgU+xe7Wax1
Rzj9PpaF119khgrIoFA8KOQ9+oovCR47HNpNAwPkKtUSXESfaasSOCjrVokdLgPH
QQyUEfAYaYLEHdrEevGV1FR9B0e095DiU1IuMhdV1J8RaOE0E6n6PElY22hUaLMC
yWYrHkN2r2KhsW4DPBGV1JBg2WTatZj0j/VZlJ8ehu9MmrCFN9McBJMH2iVXw8C9
Hpi/QyXOcv4V93SL8S8VZV1po6NZyxxrOww9mLRmdQKBgQDvbB2f9eSThwDx8arb
YFWBjCYUJhibb61ui8OpzAtaxgv/PwPKbTHg/i6FhUWeV+O5AaekuO8mYkQiiVjg
mNWvG4fhZjyccFFINlwaBOUd7/r9YVIjsYcLfmIlY7wyaj7eOlF8fEHphloSFK63
IyV7K5+t2fuHM2cT7M9rZ8EDnQKBgQDkEFzqwUPeA8MG8KMv1zozKw+fVJagVLJe
SVKWyaY9LakKLgtL7ZF8wvWW/6+KR7Dv16euXE44vySIPztwPEtdrk8nKPfdGcDO
yvEwQkWB0parmFdPxDFbU5XLuCYbiag2x5UdLr1mMAWBLPyRwjqjaO0nIMSU4xSo
myCPLyyULwKBgQC4ZbGPYIfSY9kDfpiT62cPpowxWoH7PRD7IiPpY6CfIgddaAAY
aO9QlRPpfBJ5eMGH3NFsGY7/JhHJ87SDDtMM0YxeuioWZp8DmfJni7uWyhyqB8mG
ehVDcexPVbg9r/yJlarq0JzHKdW3NTy3Che0/I04DboekCVkgC/kTf2nNQKBgD69
VaJrKm1wIX3OQ0ZM8kDTTsfpMErJIgyYJTVAIhBgeElJo2fu4gAtbfxtOHBVCpLg
g8uOryIjSzyEEKjunVkXM8U1GwLjK8x3veQlxxNQyIxKK3LRKTbThrj1Xt5ifzka
rKXLjuUGvuzrYEwE37bGjb8e35WJ5sv/aPSa6KuXAoGBAN0KZ7S6RENlRX4cjJTM
x6NYl0C4xVhqr5wLnNb9yhd5g/RxQN+KiGBBXhT3sHFQaq8DJie7A5OdLu69sNsN
S+Swkyaks9WI1dmCkGI9nerpza4y+6Nj6VYXwKF6qMQjPtyjxgSohr3p07tHFYrF
pY7H0/k8cdbDd5yox0G6vf9f
-----END PRIVATE KEY-----
"""
client_email = "starcheck-feedback@stella-project-ai.iam.gserviceaccount.com"
client_id = "108402761980489789531"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/starcheck-feedback%40stella-project-ai.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[sheets]
spreadsheet_id = "1zo_XRfqmwE1GgQcGYTUnBEmZUIdYJjGchJnKfVunmy4"
worksheet_name = "Feedbacks StarCheck"

[supabase]
url = "https://jheicqjiwijpbevmwawl.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZWljcWppd2lqcGJldm13YXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MTkwMDYsImV4cCI6MjA4NjM5NTAwNn0.muFRwt_rtU-QMHCoFsyEKfaFCEmWyCht9zVYQaBT1xE"
